In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [8]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 16.8 MB 2.1 MB/s            


In [9]:
import numpy as np

In [10]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [12]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [13]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [15]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
random_array = np.random.random((4,5))
random_array

array([[0.19583009, 0.70271411, 0.20234265, 0.08588237, 0.80141856],
       [0.00607384, 0.93264407, 0.26809364, 0.96754081, 0.30010507],
       [0.47686408, 0.48368388, 0.63745926, 0.86146072, 0.8286761 ],
       [0.75934406, 0.7883072 , 0.1209939 , 0.94541051, 0.03563431]])

In [20]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 11.7 MB 3.4 MB/s            


In [21]:
import pandas as pd

In [24]:
df = pd.DataFrame({
                    'name' : ["John" , "Alice" , "Bob" , "Rob"],
                    'gender' : ["Male" , "Female" , "Male", "Male"],
                    'age' : [45 , 20 , 30, 67]
                    })

In [23]:
df

name  gender  age
0   John    Male   45
1  Alice  Female   20
2    Bob    Male   30
3    Rob    Male   67

In [25]:
df.describe()

age
count   4.000000
mean   40.500000
std    20.436895
min    20.000000
25%    27.500000
50%    37.500000
75%    50.500000
max    67.000000

In [26]:
os.environ

environ{'ELECTRON_RUN_AS_NODE': '1',
        'SHELL': '/bin/bash',
        'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/2182,unix/unix:/tmp/.ICE-unix/2182',
        'SNAP_REVISION': '96',
        'HISTCONTROL': 'ignoredups',
        'XDG_MENU_PREFIX': 'gnome-',
        'SNAP_REAL_HOME': '/home/alexs',
        'SNAP_USER_COMMON': '/home/alexs/snap/code/common',
        'HOSTNAME': 'rog-zephyrus-g14',
        'HISTSIZE': '1000',
        'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh',
        'SNAP_INSTANCE_KEY': '',
        'XMODIFIERS': '@im=ibus',
        'DESKTOP_SESSION': 'gnome',
        'LC_MONETARY': 'en_GB.UTF-8',
        'GDK_PIXBUF_MODULE_FILE': '/home/alexs/snap/code/common/.cache/gdk-pixbuf-loaders.cache',
        'BAMF_DESKTOP_FILE_HINT': '/var/lib/snapd/desktop/applications/code_code.desktop',
        'EDITOR': '/usr/bin/nano',
        'PWD': '/home/alexs',
        'GSETTINGS_SCHEMA_DIR': '/snap/code/96/usr/share/glib-2.0/schemas',
        'XDG_SESSION_DESKTOP': 'gnome',
 

In [28]:
os.environ['USER']

'alexs'