In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [6]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [9]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [10]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [12]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
random_array = np.random.random((4,5))
random_array

array([[0.95437664, 0.11312197, 0.15202173, 0.76718406, 0.19620214],
       [0.08032485, 0.32701694, 0.17744243, 0.29881138, 0.91504743],
       [0.22682932, 0.57595435, 0.28362519, 0.7642901 , 0.08015328],
       [0.41732771, 0.4365238 , 0.90300829, 0.99791588, 0.33405817]])

In [15]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({
                    'name' : ["John" , "Alice" , "Bob" , "Rob"],
                    'gender' : ["Male" , "Female" , "Male", "Male"],
                    'age' : [45 , 20 , 30, 67]
                    })

In [18]:
df

name  gender  age
0   John    Male   45
1  Alice  Female   20
2    Bob    Male   30
3    Rob    Male   67

In [19]:
df.describe()

age
count   4.000000
mean   40.500000
std    20.436895
min    20.000000
25%    27.500000
50%    37.500000
75%    50.500000
max    67.000000

In [20]:
import os


os.environ

environ{'ELECTRON_RUN_AS_NODE': '1',
        'LESSOPEN': '| /usr/bin/lesspipe %s',
        'USER': 'alexs',
        'LC_TIME': 'en_GB.UTF-8',
        'XDG_SESSION_TYPE': 'x11',
        'SHLVL': '1',
        'HOME': '/home/alexs',
        'CONDA_SHLVL': '0',
        'DESKTOP_SESSION': 'pop',
        'GNOME_SHELL_SESSION_MODE': 'pop',
        'GTK_MODULES': 'gail:atk-bridge',
        'LC_MONETARY': 'en_GB.UTF-8',
        'SYSTEMD_EXEC_PID': '3412',
        'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus',
        'COLORTERM': 'truecolor',
        '_CE_M': '',
        'LIBVIRT_DEFAULT_URI': 'qemu:///system',
        'GTK_IM_MODULE': 'ibus',
        'LOGNAME': 'alexs',
        '_': '/usr/bin/code',
        'XDG_SESSION_CLASS': 'user',
        'USERNAME': 'alexs',
        'TERM': 'xterm-color',
        'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated',
        '_CE_CONDA': '',
        'WINDOWPATH': '2',
        'PATH': '/home/alexs/anaconda3/bin:/home/alexs/anaconda3/condabin:/usr/

In [21]:
os.environ['USER']

'alexs'