In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [6]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [9]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [10]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [12]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
random_array = np.random.random((4,5))
random_array

array([[0.32294073, 0.41816269, 0.93268927, 0.67040345, 0.67914699],
       [0.76767139, 0.23929566, 0.86637621, 0.0831893 , 0.69797558],
       [0.76733698, 0.03639552, 0.86640187, 0.72188972, 0.95010057],
       [0.00685578, 0.50443911, 0.91909291, 0.90032765, 0.25909462]])

In [15]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({
                    'name' : ["John" , "Alice" , "Bob" , "Rob"],
                    'gender' : ["Male" , "Female" , "Male", "Male"],
                    'age' : [45 , 20 , 30, 67]
                    })

In [18]:
df

name  gender  age
0   John    Male   45
1  Alice  Female   20
2    Bob    Male   30
3    Rob    Male   67

In [19]:
df.describe()

age
count   4.000000
mean   40.500000
std    20.436895
min    20.000000
25%    27.500000
50%    37.500000
75%    50.500000
max    67.000000

In [20]:
os.environ

environ{'ELECTRON_RUN_AS_NODE': '1',
        'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG',
        'SNAP_INSTANCE_KEY': '',
        'USER': 'alexs',
        'SNAP_COMMON': '/var/snap/code/common',
        'LC_TIME': 'ro_RO.UTF-8',
        'XDG_SESSION_TYPE': 'wayland',
        'SHLVL': '1',
        'HOME': '/home/alexs',
        'SNAP_LIBRARY_PATH': '/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void',
        'DESKTOP_SESSION': 'ubuntu',
        'SNAP_USER_DATA': '/home/alexs/snap/code/108',
        'GIO_LAUNCHED_DESKTOP_FILE': '/var/lib/snapd/desktop/applications/code_code.desktop',
        'GNOME_SHELL_SESSION_MODE': 'ubuntu',
        'GTK_MODULES': 'gail:atk-bridge',
        'LC_MONETARY': 'ro_RO.UTF-8',
        'MANAGERPID': '2186',
        'SYSTEMD_EXEC_PID': '2401',
        'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus',
        'SNAP_REVISION': '108',
        'GIO_LAUNCHED_DESKTOP_FILE_PID': '4069',
        'IM_CONFIG_PHASE': '1',
        'WAYLAND_DISPLAY': 

In [21]:
os.environ['USER']

'alexs'