In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [6]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [9]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [10]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [12]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
random_array = np.random.random((4,5))
random_array

array([[0.45851223, 0.48747825, 0.01666305, 0.07457612, 0.69482659],
       [0.33387961, 0.54683976, 0.26756376, 0.34310621, 0.55116143],
       [0.92025218, 0.54884821, 0.31229111, 0.06956538, 0.67774853],
       [0.25741375, 0.44418615, 0.47499411, 0.16183066, 0.42044292]])

In [15]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({
                    'name' : ["John" , "Alice" , "Bob" , "Rob"],
                    'gender' : ["Male" , "Female" , "Male", "Male"],
                    'age' : [45 , 20 , 30, 67]
                    })

In [18]:
df

name  gender  age
0   John    Male   45
1  Alice  Female   20
2    Bob    Male   30
3    Rob    Male   67

In [19]:
df.describe()

age
count   4.000000
mean   40.500000
std    20.436895
min    20.000000
25%    27.500000
50%    37.500000
75%    50.500000
max    67.000000

In [22]:
import os


os.environ

environ{'ELECTRON_RUN_AS_NODE': '1',
        'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG',
        'LC_TIME': 'en_GB.UTF-8',
        'USER': 'alexs',
        'XDG_SESSION_TYPE': 'x11',
        'SHLVL': '0',
        'HOME': '/home/alexs',
        'DESKTOP_SESSION': 'pop',
        'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/code.desktop',
        'GTK_MODULES': 'gail:atk-bridge',
        'GNOME_SHELL_SESSION_MODE': 'pop',
        'LC_MONETARY': 'en_GB.UTF-8',
        'MANAGERPID': '2952',
        'SYSTEMD_EXEC_PID': '3317',
        'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus',
        'GIO_LAUNCHED_DESKTOP_FILE_PID': '10058',
        'LOGNAME': 'alexs',
        'GTK_IM_MODULE': 'ibus',
        'JOURNAL_STREAM': '8:53805',
        'XDG_SESSION_CLASS': 'user',
        'USERNAME': 'alexs',
        'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated',
        'WINDOWPATH': '2',
        'PATH': '/home/alexs/anaconda3/bin:/home/alexs/anaconda3/condabin:/usr/local/sbin:/usr/local/b

In [21]:
os.environ['USER']

'alexs'