In [3]:
import math

In [4]:
math.pi

3.141592653589793

In [5]:
math.e

2.718281828459045

In [6]:
math.inf

inf

In [7]:
math.ceil(7.8)

8

In [8]:
!pip install numpy

In [9]:
import numpy as np

In [10]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [11]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [12]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [14]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
random_array = np.random.random((4,5))
random_array

array([[0.35208605, 0.35946292, 0.62479173, 0.67410257, 0.14242855],
       [0.50346054, 0.57896872, 0.63250126, 0.9641165 , 0.52646209],
       [0.20864718, 0.5617797 , 0.41648954, 0.40159672, 0.02723436],
       [0.92398927, 0.10771283, 0.83018207, 0.7809617 , 0.44541402]])

In [17]:
!pip install pandas

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame({
                    'name' : ["John" , "Alice" , "Bob" , "Rob"],
                    'gender' : ["Male" , "Female" , "Male", "Male"],
                    'age' : [45 , 20 , 30, 67]
                    })

In [20]:
df

name  gender  age
0   John    Male   45
1  Alice  Female   20
2    Bob    Male   30
3    Rob    Male   67

In [21]:
df.describe()

age
count   4.000000
mean   40.500000
std    20.436895
min    20.000000
25%    27.500000
50%    37.500000
75%    50.500000
max    67.000000

In [22]:
os.environ

environ{'USER': 'alexs',
        'VSCODE_WSL_EXT_LOCATION': '/mnt/c/Users/aserb/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3',
        'SHLVL': '1',
        'HOME': '/home/alexs',
        'WSL_DISTRO_NAME': 'Ubuntu-22.04',
        'WAYLAND_DISPLAY': 'wayland-0',
        'LOGNAME': 'alexs',
        'NAME': 'Zephyrus-G14',
        'WSL_INTEROP': '/run/WSL/14476_interop',
        'PULSE_SERVER': '/mnt/wslg/PulseServer',
        '_': '/home/alexs/anaconda3/bin/python',
        'TERM': 'xterm-color',
        'PATH': '/home/alexs/anaconda3/bin:/home/alexs/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/bin/remote-cli:/home/alexs/anaconda3/bin:/home/alexs/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/PowerShell/7:/mnt/c/Program F

In [23]:
os.environ['USER']

'alexs'